dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      pip install -r requirements-api-generator.txt;
    fi

script:
  - nosetests -v tests/backlog
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      nosetests -v tests/api_generator;
    fi
